@'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomodoro-timer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pomodoro
  template:
    metadata:
      labels:
        app: pomodoro
    spec:
      containers:
      - name: pomodoro
        image: swapnali2311/pomodoro-timer:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pomodoro-service
spec:
  type: LoadBalancer
  selector:
    app: pomodoro
  ports:
  - port: 80
    targetPort: 80
'@ | Out-File -Encoding UTF8 k8s-deployment.yaml
